#!/usr/bin/python
# -*- coding: utf-8 -*-

import os

ACTION_ENCRYPT = 0
ACTION_DECRYPT = 1
ACTION_SAVE = 2
ENCRYPTED_CONTENT = 1
DECRYPTED_CONTENT = 0
NORMAL_STATE = "normal"
DISABLED_STATE = "disabled"
CURRENT_WORKING_DIRECTORY = os.getcwd()
DATABASE_FILE_NAME = "\\passwords.db"
DATABASE_FILE_PATH = CURRENT_WORKING_DIRECTORY + DATABASE_FILE_NAME
PASSWORD = "chelseafan93"
CORRECT_PASSWORD = 0
INCORRECT_PASSWORD = 1
NONE_PASSWORD = 2